### ISSUE TITLE
Sample size is less than 5,000 so using LOOCV instead of 5-fold CV.

### ISSUE THREAD

**Issue by psychrb** [rgcgithub/regenie#104]
For a cohort of ~2,700 samples and a relatively rare variant, I am running REGENIE /2.0.2
For Step 1, I receive warning: Sample size is less than 5,000 so using LOOCV instead of 5-fold CV.
1) Is there any way to suppress this automatic LOOCV. I didn't enter the flag?...Necessary to use it?
Is this automatic LOOCV for smaller sample size in all REGENIE versions, previous? Prior to /2.0.2?

For Step 2:
2) An error ensues:
ERROR: Zeros occured in Var(Y) during logistic regression.

NOTE: I've reviewed the website info on small samples sizes in FAQ, have filtered out/excluded samples for missingness and samples with low variant frequency.Comments? Thoughts to resolve?

And, I also get this same error (ERROR: Zeros occured in Var(Y) during logistic regression) when I run the regression without covariates, too, so not attributable to covariates, therefore.

**Comment by psychrb** [comment]
Please also note if I use the --ignore-pred flag for Step2 then the regression does run to completion..So the issue seems to be inclusion of the predictors generated by the LOOCV

**Comment by joellembatchou** [comment]
Hi,

(1) We enforce LOOCV instead of K-fold CV for small sample size as we are trying to avoid having folds with no cases (which is more likely for highly unbalanced traits). This has been enforced in all previous releases (from 7a138d3b039a9049f057fa5317618498f416f2da).

(2) Convergence issues for logistic regression tend to occur more often for smaller sample sizes with lower case counts. While we have worked on reducing this, it can still occur (though since Regenie was developed for large-scale data sets, it should not be a major issue in such applications). From our LOOCV to K-fold CV comparisons, the step 1 LOCO PRS should be fairly similar so most likely switching to K-fold CV won't address this. We will add an option in future releases to force K-fold CV for small sample sizes.

Cheers,
Joelle
