### ISSUE TITLE
Is there a smart way to limit step 2 to a different chromosome for each of the phenotypes in my --phenoColList?

### ISSUE THREAD

**Issue by cqgd** [rgcgithub/regenie#128]
Hi Joelle, Jonathan and team,

Many thanks for this great tool. Works very well in situations where Bolt-LMM was getting a bit resource heavy. 

Could I quickly check with you if there's an efficient way to run step 2 if I'm only interested in association tests for a single chromosome, where that chromosome differs between phenotypes? 

In essence, is there a sensible way I can restrict the association tests to a different chromosome for each of 22 phenotypes in my  `--phenoColList` (e.g. to chr1 for pheno1, chr2 for pheno2, chr3 for pheno3)? Or would you recommend I run 22 separate step 2 commands, each with a different phenotype and a `--bgen` for a different chromosome?

Any insights on how I might improve REGENIE's performance (compared to the naive scenario of just running each phenotype genome-wide) would be great.

Thanks again for all your work,

Chris

P.S.: Finally, if I may suggest one thing to improve usability, adding a reminder of the total number of blocks that need to be processed (so ouputting "block [247 / 512] : 151 snps  (4142ms)" instead of just "block [247] : 151 snps  (4142ms)")  would eliminate a good amount of scrolling around between the top and bottom of the output log as I gauge when my job might finish! Would make it easier to assess progress at a glance.

**Comment by joellembatchou** [comment]
Hi Chris,

There is no straightforward way to test different chromsomes for different sets of phenotypes within the same run. Your idea of using a different --phenoColList for each step 2 run on a single chromosome sounds very sensible since each phenotype is tested on a separate chromosome.

We have implemented your suggestions of printing block number as well as total number of blocks at each block iteration in the log.

Thanks,
Joelle

**Comment by cqgd** [comment]
Many thanks for your quick response Joelle,

That's good to know, I'll proceed with separate `--phenoColList`s. Really appreciate the log change too!

Best wishes,

Chris
