### ISSUE TITLE
plink2 binary data and regenie

### ISSUE THREAD

**Issue by seppinho** [rgcgithub/regenie#141]
HI Joelle,

I converted the VCF data from the Michigan Server to the plink2 format (main options: `vcf dosage=DS --make-pgen --double-id`) and compared the R2 and MAF infos from the `*.pvar` file to the `*.regenie` file. Looks like there are minor discrepancies (might due to floating point representation?) that can result in INFO values > 1. 

It doesn't make a big difference but just wanted to let you know. 

e.g.
`MAF=0.40004;R2=0.99955`
`A1FREQ=0.400079 INFO=1.00553`

`MAF=0.00129;R2=0.4940`
`A1FREQ=0.00127838 0.503177`

Best.
Sebastian

**Comment by joellembatchou** [comment]
Hi Sebastian,

With PGEN input format with dosages present, Regenie computes the Mach R^2 info score, which can give info score values > 1 (see [here](https://static-content.springer.com/esm/art%3A10.1038%2Fnrg2796/MediaObjects/41576_2010_BFnrg2796_MOESM3_ESM.pdf)). What command did you use to compute the "R2" value you are reporting above and comparing to Regenie's?

**Comment by seppinho** [comment]
Hi Joelle, 
Thank you so much for your answer. Regarding your question: I did a simple comparison between  sites in my initial VCF files and the final regenie file. (e.g. R2 0.87 vs 1.05 or MAF 0.00087 vs 0.000867918). If helpful, I can run a script over all chromosomes.

**Comment by joellembatchou** [comment]
To determine if it is perhaps due to the different input formats, it would be clearer if your comparison was made based on the exact same input file. 


So if in Regenie you ran
```
regenie --pgen pgen_prefix --step 2 --extract list_sites.txt --write-samples --out regenie (+specify phenotype/covariates options)
```

where `list_sites.txt` is a list of variants to test (perhaps those where you currently see the most discrepancy. Then  in PLINK2 you can run
```
plink2 --pfile pgen_prefix --extract list_sites.txt --freq cols=+machr2 --out plink
```

And then check the AAF & Mach R^2 imputation info score between the two output files. 

Note that this assumes the same samples are used in both runs (running Regenie for a single trait and using `--write-samples` and passing those sample IDs to PLINK2 should guarantee that is the case).
