### ISSUE TITLE
burden test || similar to skat-o || use all SNPs with gene annotation

### ISSUE THREAD

**Issue by sariya** [rgcgithub/regenie#159]
Dear regenie team,

I am interested to perform collapsing/burden test similar to skat-o, skat gene-based analysis. I annotated SNPs using ANNOVAR tool. 

Is there a way regenie helps to create files format needed in mask, annotation for an output from the annovar file?

Generally, using tools such as GMMAT for gene-based analysis, annotation file works (SNP-gene in columns). 
However, regenie needs a mask file. How do I tell regenie to take all SNPs annotated within a gene without any distinction or masks?

I have following types of func annotation for my SNPs using annovar

```
downstream
exonic
exonic;splicing
intergenic
intronic
ncRNA_exonic
ncRNA_intronic
ncRNA_splicing
splicing
upstream
upstream;downstream
UTR3
UTR5
```
thanks

**Comment by joellembatchou** [comment]
Hi,

Regenie does not currently support variance-component type of tests like SKAT. This is a feature we have planned to add in later versions. If you don't want to use variant annotations when building masks, you can just define a general annotation in the file going to --anno-file, e.g.
```
rsid1 GENE1 ALL
rsid2 GENE1 ALL
...
```

You can also set `--aaf-bins 0.99999999` so that the mask will include all variants specified in your gene set.
