### ISSUE TITLE
Issue with Regenie/1.0.5.2

### ISSUE THREAD

**Issue by BinglanLi** [rgcgithub/regenie#17]
Dear Regenie developers,

How are you doing? 

I am really excited to learn about Regenie and started using it about several weeks ago. It has been working well until we updated to version 1.0.5.2 the other day. (we had an issue compiling 1.0.5.3 and am still trying).

When I ran Regenie/1.0.5.2, I ran into this unexpected error:
```
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
 what(): boost::filesystem::canonical: No such file or directory: "/directory/regenie_step1_fit_bin_out_1.loco"
```
Only step 1 has this issue. The issue can be resolved by creating an empty output file.

Is this a specific issue to 1.0.5.2? What is going on with this error?

**Comment by joellembatchou** [comment]
Hi Binglan,

This was fixed in Regenie v1.0.5.3 (the error is due to boost::filesystem::canonical requiring for the .loco file to exist, which it doesn't as it hasn't yet been created). 

What error are you getting when compiling v1.0.5.3? You may need to run `make clean && make` when compiling the new version
