### ISSUE TITLE
Binary and categorical predictors

### ISSUE THREAD

**Issue by lportas78** [rgcgithub/regenie#21]
Dear Regenie developers,

Currently I and my colleagues are trying to use Regenie in our projects but it is not clear to us how binary and categorical predictors are handled. Is it possible to specify that the variables included in the model are binary or categorical?

**Comment by joellembatchou** [comment]
Hi,


Regenie currently can handle quantitative and binary phenotypes (i.e. categorical variables with at most 2 categories). For binary phenotypes, this can be specified in Regenie using flag `--bt`. (Details and examples can be found on the Regenie webpage)


Cheers,
Joelle

Sent from my iPhone

On Jul 31, 2020, at 11:18 AM, lportas78 <notifications@github.com> wrote:




﻿

Dear Regenie developers,
Currently I and my colleagues are trying to use Regenie in our projects but it is not clear to us how binary and categorical predictors are handled. Is it possible to specify that the variables included in the model are binary or categorical?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by fmurgia** [comment]
Hi Joelle,
I was wondering how Regenie handles categorical covariates (not the outcome) with more than 2 levels (e.g. 27 levels)? Is there a way, similar to Bolt-lmm, to specify that a predictor with more than 2 levels is a categorical variable?
Best,

Federico

**Comment by joellembatchou** [comment]
Hi Federico,

Sorry I misread your question. Regenie currently doesn't directly handle categorical covariates, I will add this to the list of enhancements we can add to the software. For now, you would need to convert these to indicator variables prior to calling Regenie.

Cheers,
Joelle

**Comment by samkleeman1** [comment]
Just to follow-up on this, what is the correct approach to include a covariate with, for example, 10 levels. Should this be split into ten columns, effectively one-hot encoding the covariate? I was hoping to include the assessment centre as a covariate in UK Biobank analysis, as this is quite a common approach (e.g. the BOLT-LMM marker paper includes this as covariate) to account for some geographical variation. 

As a linked question - in your paper you mention using age as a covariate for binary associations and I was wondering how you defined age in this context. For continuous traits (e.g. LDL) I assume you would define age as age of subject when blood sample was taken (this is mostly date of recruitment but there are multiple potential blood sampling points for UK Biobanks subjects), but for binary traits (e.g. heart attack) where you are measuring hospital diagnoses coded up until the most recent data release, do you define age as the age the subject would be at the most recent data release (if still alive)? This is because not all subjects were recruited at the same time. I note that SAIGE used birth year as a covariate instead of age to circumvent this question somewhat.

**Comment by rgcgithub** [comment]
Yes - one-hot encoding for categorical variables.

The precise use of covariates will depend on the phenotype. What you suggest seems reasonable.

**Comment by joellembatchou** [comment]
Hi,

Regenie v2.0.1 can now handle categorical covariates using `--catCovarList` which takes in a comma separated list of categorical variables.

Cheers,
Joelle
