### ISSUE TITLE
Lower pThresh cut-off to save time for association test to binary traits 

### ISSUE THREAD

**Issue by Shicheng-Guo** [rgcgithub/regenie#241]
Dear Joelle, 

I expected lower pThresh (default=0.05) to some value like 5.0x10^-8 could save some time for binary traits analysis since less SPA correction would save lots of time for the analysis. However, I didn't find too much time was saved. I am wondering how to understand it. Can you share some vision about pThresh cut-off with running time for binary analysis with --SPA. 

Thanks. 

Shicheng

**Comment by joellembatchou** [comment]
Hi Shicheng,

How many of the variants in your initial output file have p-value below 0.05? And how many are you testing overall? We haven't experiemented with how changing the threshold `--pThresh` from 5% to 1% would decrease total runtime but I expect it would not make too much of a difference since you would expect under the null that for ~95% of the variants would not use SPA so the majority of the runtime would be mostly reading in the variants and running the logistic regression score test.

Cheers,
Joelle
