### ISSUE TITLE
duplicates in `--anno-file`

### ISSUE THREAD

**Issue by Ojami** [rgcgithub/regenie#262]
Dear Joelle,

REGENIE doesn't allow duplicates in `--anno-file` and complains:
```
ERROR: duplicate variant annotations at line X.
```
Why isn't this possible? There can be cases where several overlapping categories may exist in annotation file (e.g. CADD > 20 and CADD > 30), and all can be of interest. While this can be tackled by including all overlapping categories in the same mask, I was wondering if there is a better solution, since this can be complicated when there exists several categories. 

Thanks!
Best/Oveis

**Comment by joellembatchou** [comment]
Hi Oveis,

We do not allow duplicate annotation entries for the same variants with the same gene (but you can have the same variant have different annotations for different genes). You could bin the CADD score into non-overlapping intervals (eg 0-10,10-20,...) so that you could define masks which combine different bins, e.g.
```
Mask1 [0-10],[10-20]
Mask2 [10-20],[20-30][30-40]
```
Cheers,
Joelle
