### ISSUE TITLE
"ERROR: Throw location unknown" when running gene-based tests

### ISSUE THREAD

**Issue by jimmyzliu** [rgcgithub/regenie#318]
Hi,

When running step2 of rare-variant gene-based tests, every now and again regenie would reach a gene and then crash with the following error:

 set [148/1355] : ENSG00000181609 - 376 variants...
     -reading in genotypes, computing gene-based tests and building masks...WARNING: Firth/SPA correction failed for 1/63 variants.ERROR: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: N5boost16exception_detail10clone_implINS0_19error_info_injectorISt14overflow_errorEEEE
std::exception::what: Error in function boost::math::pdf(const chi_squared_distribution<d>&, d): Overflow Error

I'm using v3.1.2 pre-compiled centos7 version with the following options:
  --step 2
  --bgen
  --ref-first \
  --sample
  --phenoFile
  --phenoCol
  --covarFile
  --covarColList 
  --bt
  --firth
  --approx
  --pred
  --anno-file
  --set-list
  --mask-def
  --aaf-bins 0.01,0.001,0.0001
  --vc-tests skato,acato-full
  --vc-maxAAF 0.01
  --write-mask-snplist
  --bsize 400 \
  --out

Any help very muchly appreciated - thank you!

Jimmy

**Comment by joellembatchou** [comment]
Hi Jimmy,

This seems to be a bug in the code; will look into it and let you know when a fix is released. Thank you for catching this!

Cheers,
Joelle

**Comment by changlubio** [comment]
Hi, 

Adding to the thread, I have encountered a similar problem when running step 2 of gene-based tests:

set [697/1973] : GREM2(ENSG00000180875) - 94 variants...
     -reading in genotypes and building masks...done (258ms) 
     -computing association tests...done (9ms) 
 set [698/1973] : GRHL3(ENSG00000158055) - 333 variants...

terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'

I'm using REGENIE (v3.1.1) from the UKBiobank with the following options:

--step 2 \
--pred \
--bgen --ref-first \
--sample  \
--keep \
--phenoFile \
--covarFile \
--phenoCo
--covarColList  \
--set-list   \
--anno-file  \
--mask-def \
--aaf-bins 0.01,0.001
--bsize 1000 \

Thanks
Chang

**Comment by joellembatchou** [comment]
Hi Chang,

Could you try with the most recent release (v3.1.3) and see if you still get the error? 

Thanks,
Joelle

**Comment by joellembatchou** [comment]
Hi Jimmy,

This should now be fixed in [v3.1.4](https://github.com/rgcgithub/regenie/releases), please let me know if that is not the case.

Cheers,
Joelle

**Comment by jimmyzliu** [comment]
That's awesome, thank you Joelle!

**Comment by dwightman** [comment]
Apologies for commenting in a closed thread. I wanted to add my experience with this issue in case it would be helpful for other people.

I also experienced this problem while perfoming SKATO gene-based tests on the WES data on the UKB RAP. I got the following errors for some genes:
```terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >```
```
ERROR: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: N5boost16exception_detail10clone_implINS0_19error_info_injectorISt14overflow_errorEEEE
std::exception::what: Error in function boost::math::pdf(const chi_squared_distribution<d>&, d): Overflow Error
```

I tried the analysis with REGENIE v3.1.1,  REGENIE v3.1.4, and REGENIE v3.2.5 but got the same error. When I removed the genes that caused these errors from the analysis using --exclude-setlist then it ran fine (using 32 GB of memory). I then ran the gene that caused the error using --extract-setlist but chose more memory (128GB) and this analysis ran OK. I think my problem was caused by certain genes using more memory than available on my instance. I don't know how feasible this would be but it would be great for regenie to skip the genes that are taking more memory than available and finish the rest of the genes rather than throwing an error and losing all of the analysis results of the previous genes.

Cheers,
Doug
