### ISSUE TITLE
When the number of variants exceeds 5 million, how should the parameters of step 1 be set ?

### ISSUE THREAD

**Issue by xuqian007** [rgcgithub/regenie#340]
Hi,
 I had some problems when I use regenie, specifically my genotype data included about 7 million variants and the samplesize was 200,000, but after about 5 days of running Step 1, I didn't get any results. The code as follows:
regenie \
--step 1 \
--bed  imputed \
--covarFile cov.txt \
 --phenoFile phe.txt \
--remove  fam_id_remove.txt \
--exclude problem_variant_id.txt \--bsize 2500 \
--cv 500  \
--bt \
--lowmem \
--lowmem-prefix imputed_tmp_rg \
--threads 8 \
--out imputed_step1_out 
The second question is whether the input files in step 1 and step 2 are the same, that is the input file in step 2 is "--bed imputed"
Thank you so much!
Cheers, 
xuqian

**Comment by joellembatchou** [comment]
Hi Xuqian,

Please check the [recommendations for Step 1](https://rgcgithub.github.io/regenie/faq/#step-1) (we suggest using ~500K directly genotyped markers) as well as block size of 1,000.  Also, instead of specifying 500 cross validation folds, I'd recommend using LOOCV directly (ie `--loocv`) for which we have an efficient implementation.

The genotype files used in step 1 & 2 do not have to be the same (e.g. step 1 on array data and step 2 on imputed data). See [here](https://rgcgithub.github.io/regenie/recommendations/#step-2) for more details.

Cheers,
Joelle
