### ISSUE TITLE
Covariates

### ISSUE THREAD

**Issue by ZhiyiZhu0226** [rgcgithub/regenie#390]
So I wonder what's the best practice to include sex as a covariate. I'm running a GWAS on the UKBiobank, and I'm trying to use the following as covariates: 1st 20 PCs, age, age^2, sex, age * sex, age^2 * sex. What I'm not sure is how to add the last 3 terms as covariates. My covariate file looks like this: 
![image](https://user-images.githubusercontent.com/75864020/221040048-b14090ab-e8a6-4b76-9e53-e20aa52bf146.png)

The code I used to run regenie is:
./regenie --step 1 --bed /bed/ukb_snp_chrall_filtered --extract qc_pass_all.snplist --keep /qc_pass_all.id --phenoFile sex_specific_tg_hdl.cleaned.pheno --covarFile sex_specific_tg_hdl.cleaned.cov --apply-rint --bsize 1000 --lowmem --lowmem-prefix tmpdir/regenie_tmp_preds_all --out ukb_step1_all

Since sex is encoded as 0/1, do I need to add the parameter --catCovarList SEX to specify that the sex covariate is categorical? Also I'm confused how regenie includes age*sex as a covariate, as suggested in the regenie paper (https://www.nature.com/articles/s41588-021-00870-7). Is it literally a column in the covariate file that's calculated by age * sex (so, when female = 0, male = 1, the sex * age of a 56 year old female will be 0)? It doesn't make much sense to me since sex is a categorical variable, and I'm not sure what the product of a categorical variable and a quantitative variable would mean.

**Comment by joellembatchou** [comment]
Hi,

From your snapshot of the covariate file, you've already pre-computed the agexsex (SEXAGE), age^2xsex (SEXAGE2) variables so it is fine to specify them as you have done in REGENIE (from your command, REGENIE will by default include all columns [besides FID/IID] as quantitative covariates in the analysis). Also, since sex is a binary 0/1 variable, it makes no difference including it as categorical vs quantitative.

Cheers,
Joelle
