### ISSUE TITLE
NA values in the phenotype (include or exclude) getting different association results!!

### ISSUE THREAD

**Issue by msarguru** [rgcgithub/regenie#43]
Dear developer,

With regards to the phenotype file (used in step1 and step2), we are facing a dilemma as to whether 
i) include the individuals with missing phenotype value (QT, quantitative trait) that are coded as NA, thereby matching the order with sampleID order in the genotype, 
ii) **or**; remove the individuals with NA in the phenotype file altogether

As we have been getting different results if we include or remove individuals with missing phenotype. Should we adopt the `--strict` option and not use `--force-impute`,  just to be sure that the missing individuals are not considered. 

Many thanks in advance for your comment/suggestions.

Regards
Murali

**Comment by joellembatchou** [comment]
Hi Murali,

Missing data is handled differently in step 1 and step 2. In step 1, missing values are imputed with the sample average. In step 2, they are dropped by default (unless you use `--force-impute`). 

With a single phenotype, `--strict` is enabled by default (i.e. samples with missing phenotype are dropped) and so the results will be the same (in step 1 and step 2) to those from removing missing individuals from the phenotype file and running Regenie on the resulting file. 
With multiple traits, the results will differ since step 1 will use mean-imputation. Also, `--strict` with multiple traits would drop individuals with missing values at **any** of the traits.

In general, we recommend to run Regenie on traits with similar missing data patterns (in the [Regenie biorxiv paper](https://www.biorxiv.org/content/10.1101/2020.06.19.162354v1), we found that the multi-trait analysis using mean-imputation in step 1 gives very similar results to the single trait analysis dropping individuals with missing phenotypes [there the traits we analyzed had up to ~15% missingness - Table S2/S6 of paper]).

Cheers,
Joelle

**Comment by msarguru** [comment]
Dear Joelle,

Thank you for the comments. 
We are running single trait only so by default any missing individuals should be removed, so that the results from step2 is expected to be identical. 
Also in the preprint you state "Hence,
we implement an alternative approach where in both the null fitting step and the association testing
step, all samples with missingness at any of the P phenotypes are dropped." 

However, we do see minor differences in the estimates, as below. Is there an explanation as to why they are different. 
And which strategy do you suggest keeping. Also our samples are not that big (its around 2K) after missingnes (depending on the phenotype they vary between 1.5K-1.8K). 
Is there any benefit of keeping the NA (Option1), compute the necessary mertrics in step1 (possibly better account for any relatedness structure) and remove the NAs by default (as single phenotype is analysed) in step2. 

Any suggestions/comments would be greatly appreciated. 

`
Analysis | CHROM | GENPOS | ID | ALLELE0 | ALLELE1 | A1FREQ | TEST | BETA.Y1 | SE.Y1 | CHISQ.Y1 | LOG10P.Y1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Option1With NA | XX | YY | XY | Z | ZZ | A1FREQ | ADD | -0.0680002 | 0.112507 | 0.365308 | 0.263147
Option2NA removed | XX | YY | XY | Z | ZZ | A1FREQ | ADD | -0.0437876 | 0.113955 | 0.147649 | 0.154411

`

Thanks
Murali

**Comment by joellembatchou** [comment]
Hi Murali,

I've added a test example that has missing values (i.e. NA) for one of the traits (10% of the values for the trait are missing).
```
> head example/phenotype_bin_wNA.txt
FID IID Y1 Y2
1 1 1 1
2 2 0 0
3 3 0 0
4 4 0 0
5 5 0 1
6 6 NA 1
``` 

There is now a test script (test/check_na.sh) which runs Regenie (step 1 & step 2) on the original phenotype file (in single trait mode by specifying `--phenoCol Y1`) and compares that to running Regenie on a new phenotype/covariate file where individuals with NA have been removed. At the end of the script, it compares the resulting summary stats files.
```
test/check_na.sh --path .
```
(note: you may have to use  `chmod u+x test/check_na.sh` before running command above)

It is important to specify a single phenotype column to analyze when using a phenotype file with multiple phenotypes (i.e. using `--phenoCol Y1`) otherwise the two analyses will not match. You can check this using
```
test/check_na.sh --path . --all
```

The script by default analyzes runs Regenie in binary trait mode. You can run it in quantitative trait mode using 
```
test/check_na.sh --path . --qt
```

For the discrepancy you are seeing, can you either include the Regenie command you are using or double check that you either  have a phenotype file with only 3 columns (i.e. FID IID Trait) or are using a single `--phenoCol Trait` to run Regenie with a single trait.

**Comment by msarguru** [comment]
Hi Joelle,

Thank you for the explanations. 
Will look in to the test script. But little note on the tried options (below) in running the step1 and step2. 
In terms of the phenotype, we always use only single trait and not really in to the multi-trait scheme

Head of the phenotype, with 3 columns (FID IID Trait):
FID	IID	QT
123	123	-0.901
1234	1234	-1.473
12345	12345	NA

For step1: 
`/regenie \
 --step 1 \
 --bed variantQCed.new_ID_finalQC \
 --p regenie.QT1.PHE \
 --b 1000 \
 --threads 4 \
 --o regenie.QT1.PHE.step1`

For step2:
`/regenie \
  --step 2 \
  --bed chr22.variantQCed.sampleQCed \
  --p regenie.QT1.PHE \
  --b 200 \
  --thread 4 \
  --pred regenie.QT1.PHE.step1_pred.list \
  --o regenie.QT1.PHE.step2.chr22.output 
`
I am not entirely sure of the threshold when you mention "We have not explored this for such small samples but I expect you'd need to consider a lower threshold for the % missing." 

Considering the small N, from experience would you suggest including them all for a better estimates of GRM [accounting for relatedness (as we do have few related ind. in our data)] or remove them (400-700 individuals depending on the phenotype) and it does not have a major impact on the GRM.

Many thanks again
Regards
Murali

**Comment by joellembatchou** [comment]
Hi Murali,

As mean-imputation is used for missing values in the phenotype data in step 1, it is important to consider how much missingness should be tolerated in the phenotype data so as not to lead to large differences in the association results compared to removing the missing data from the analysis. From our experiments on UK Biobank, we found that even with up to 18% missing, the results were quite robust to the mean-imputation scheme used in step 1. For such small sample sizes, we have not done this evaluation but I expect that the threshold for the % missing should be lower (i.e. less than 18% as each sample would carry more weight in a sample with N=2K compared to N=408K in the pre-print). 

Importantly, the purpose of adding a mean-imputation scheme in step 1 is to facilitate the analysis of multiple traits which have varying missing data patterns. As here you have a single trait, it is preferred (and done by default in Regenie) to drop missing values both in step 1 and step 2.

Note: From the commands that you mentioned, it seems you are running an older version of Regenie (<1.0.5.3). I'd recommend updating to the most recent version as the option `--strict` was only enabled by default with single trait runs in later versions (which may be why you are not getting the same results including/excluding the missing values from the phenotype file).

Cheers,
Joelle
