### ISSUE TITLE
Product suggestion: SNP has low variance error

### ISSUE THREAD

**Issue by rdey-insitro** [rgcgithub/regenie#487]
Hi, this is more of a product suggestion. As a regular user of REGENIE, I come across this particular error quite often when running step 1 `ERROR: !! Uh-oh, SNP rs113795383 has low variance (=0.000000).` 

I understand this is due to the SNP being monomorphic among the subjects present in the phenoFile. To get around this, every time I need to run REGENIE on different subsamples of the same dataset, I need to first filter the BED file to remove SNPs that are monomorphic to that particular set of subjects with non-missing phenotypes. This adds quite a bit of redundant computation (and also annoying to filter the bed file every time) which becomes an hindrance in using REGENIE as part of larger workflows. 

I think it is quite easily fixable at the software end by just ignore SNPs that have "low variance" instead of throwing an error and stopping the entire workflow (or have an option to do so).

If you could please address this issue in the REGENIE software, it will help the users immensely and simplify many workflows that use REGENIE. Or if you could guide me to some other solution/argument that I may need to pass on to REGENIE that enables the skipping of the low variance SNPs (essentially monomorphic), that will be helpful too.

Thanks in advance. Really appreciate the work behind this software.

**Comment by joellembatchou** [comment]
Hi,

Some of the parameters used in REGENIE are dependent on the total number of variants analyzed in step 1 being known at the start of the run hence why we throw out an error when this case happens instead of just ignoring the variant. What command are you using as pre-QC to avoid monomorphic variants? Perhaps using a higher minimum MAC filter (in addition to a MAF filter) would help reduce the cases of monomorphic variants present after sub-sampling the data?

**Comment by joellembatchou** [comment]
Perhaps you could split the phenotypes into batches where in each batch the phenotypes have fairly similar missingness patterns and then apply the MAC filter in each batch. This should avoid the MAC error in step 1.

While it is straightforward to filter out variants in step 1, we only know if a variant passes/fails MAC filter once it is read so that would mean having first to do a pass through the whole genotype data and then another pass to run the step 1 models. Running a pre-QC step on the genotype data to get that list of variants passing MAC filter would be about the same computational burden so we would recommend doing that instead. But for your use case, I think creating batches across the phenotypes would be more sensible (you could also then run REGENIE within these matches with the multi-trait mode).

**Comment by MatthewMaher** [comment]
rdey* wrote: 
" _Right now we need to perform MAC filtering for each phenotype and create new BED files before running REGENIE step 1_"

I think that's making it harder than need be (recreating the entire/huge BED fileset).   Just getting the list of SNPs with `--write-snplist`, and then supplying the same to regenie with `--extract` should suffice.   This is as explained [here](https://rgcgithub.github.io/regenie/faq/#step-1) and [here](https://rgcgithub.github.io/regenie/recommendations/#exclusion-files).

Joelle will please correct me if not true.

Perhaps that error message ("low variance") could contain a URL linking right to that documentation section.

**Comment by rdey-insitro** [comment]
Thanks. This helps a lot. Please close this issue whenever convenient.
