### ISSUE TITLE
Run Regenie on X chromosome

### ISSUE THREAD

**Issue by xliaoyi** [rgcgithub/regenie#555]
Hello,

According to the Regenie documentation:

_To include X chromosome genotypes in step 1 and/or step 2, males should be coded as diploid so that their genotypes are 0/2 (this is done automatically for BED and PGEN file formats with haploid genotypes). Chromosome values of 23 (for human analyses), X, Y, XY, PAR1 and PAR2 are all acceptable and will be collapsed into a single chromosome._

However, for step 2, the input file is a .bgen file. Is there any way to modify the X chromosome .bgen file to code males as diploid?

Thanks,
Liaoyi

**Comment by LeahBoettger** [comment]
Hi Liaoyi, 

I believe recoding them into .pgen files might work for this step? At least that is what I'm planning on doing. 

I'm actually struggling with the conversion to a .bed format for step 1: I'm QC'ing my genotype data before (as recommended) and am doing this individually for females and males for the X chromosome. The problem is that when converting .bgen to .bed, dosage information for males is set to integers/ missing values. What would be the best way around this?

All the best and thank you,

**Comment by joellembatchou** [comment]
Hi Liaoyi,

Perhaps you can convert between BGEN to PGEN for the non-PAR chrX regions (e.g. using PLINK2)?

Cheers,
Joelle

**Comment by xliaoyi** [comment]
Thanks for letting me know! I will use pgen file for running gwas then.

**Comment by chrchang** [comment]
@dvh13 fyi, there was a plink2 bugfix last week affecting chrX/chrY .bgen export; that bug may have been a source of your problems.
