### ISSUE TITLE
Low variance issue only present in sex-specific run of step 1

### ISSUE THREAD

**Issue by Osmluke** [rgcgithub/regenie#570]
Hi all,

I was testing what step 1 pred_lists would perform best in step 2 to account for polygenic variation in my data, but I ran into a particular issue:

 block [451] : 1000 snps  (6ms)
   -residualizing and scaling genotypes...done (5ms)
   -calc working matrices...done (672ms)
   -calc level 0 ridge...done (196ms)
 block [452] : 1000 snps  (6ms)
   -residualizing and scaling genotypes...done (6ms)
   -calc working matrices...done (675ms)
   -calc level 0 ridge...done (168ms)
 block [453] : 1000 snps  (6ms)
   -residualizing and scaling genotypes...done (5ms)
   -calc working matrices...done (686ms)
   -calc level 0 ridge...done (166ms)
 block [454] : 1000 snps  (6ms)
   -residualizing and scaling genotypes...done (5ms)
   -calc working matrices...done (680ms)
   -calc level 0 ridge...done (161ms)
 block [455] : 377 snps  (5ms)
   -residualizing and scaling genotypes...ERROR: !! Uh-oh, SNP rs75496483;rs142242858_CTG_C_hwe_ctrl has low variance (=0.000000).

The command I used:
```
./regenie --step 1 --pgen SNP_plink2_DP20_cases_controls_qc1_geno-90 \
 --covarFile file_prep/test1/SNP_regenie_DP20_cases_controls_qc1_geno-90.covar \
--phenoFile file_prep/test1/SNP_regenie_DP20_cases_controls_qc1_geno-90.pheno \  
--bt \ 
--bsize 1000 \
--sample file_prep/test1/SNP_regenie_DP20_cases_controls_qc1_geno-90.samples \
--extract file_prep/test1/SNP_regenie_DP20_cases_controls_qc1_geno-90.subset_variants.list \ 
--phenoCol CaConRel \
--covarCol Age \
--out step1/male_specific/SNP_regenie_DP20_cases_controls_qc1-geno90_men_covar-age_ld-200kb-0.5 \
--sex-specific male
 ```
 
 The --pgen argument is using a set of plink files with 26.9 million variants, with only a genotyping rate of 90% applied. The --extract is taking out variants from these pfiles which have passed the following filters:
 1. Genotyping rate of 90%
 2. minimum MAF of 5%
 3. HWE 1e-6 (with midp adjustment)
 4. LD pruning with 200kb window size and r2 of 0.5
 
 In total, the --extract variant list has about 585k variants

When running the exact same command without using the --sex-specific argument, the pred.list is created without issue.

Sorry in advance if these questions seem basic or trivial, I'm still relatively new to SNP analysis.

From all of this I have a few questions:
1. Is there anything to do here other than to tweak the LD pruning parameters to account for the low variance? 
2. Considering I have 26.9 million variants across approximately 800 samples I want to test in step 2, both through logistic/firth regression and the gene-based tests, what would be the optimal bsize and number of variants in my subset for step 1? 
3. For sex-specific GWAS, is it important to run step 1 using the sex-specific argument? Or would it be fine to use a step 1 run on both sexes at once with sex as a covariate and then running step 2 with the sex-specific argument?
4. On an unrelated note, when should --write-null-firth be used? I'm already running --firth in step 2 without --approx as computational burden is not an issue. I was also considering increasing the max-iterations for when a test fails (quite rare), maybe to about 35? Would this cause any issues?

**Comment by Ojami** [comment]
Please see #497 for best practice on using high quality SNPs for step 1. Also please note that feeding REGENIE with those flags is computationally intensive, instead use PLINK for first LD-prune your variants ([see also here](https://rgcgithub.github.io/regenie/recommendations/#step-1)) and then use them for downstream analyses (in REGENIE). 

- Low variance error happens most probably because of  AAF = 0.
- I would guess in case of smaller sample size, a larger `bsize` (maybe ~2500) would be more favourable. However, in practice REGENIE is robust to smaller sample sizes even with `bsize=1000`:

> Can regenie be run on small sample sizes?
For quantitative traits, we have not obtained issues running regenie on small data sets. For binary traits, we have obtained successful runs of regenie (step 1 and 2) on data sets with as little as 300 samples. 

- Yes it's important to use step 1 predictions generated by `--sex-specific` option in step 2. Note that REGENIE uses genetically inferred sex from the sample/psam/... files and not from your covariates (so make sure they're consistent, e.g. you removed those with a mismatch between self-reported/genetic sex).

- `--write-null-firth` and it's related option `--use-null-firth` can reduce CPU-time, however if it's not a computatioanl burden for you, it can be avoided. Same goes to max-iteration or step size in GLM with Firth's penaly: if GLM converges at a reasonable computatioanl price, then it seems reasonable to increase iteration and lower down the step size.

Best/Oveis

**Comment by Osmluke** [comment]
Thank you very much, I'll experiment with the more stringent genotype rate and increasing bsize to 2500 for step 1.

Since computational burden isn't an issue at the moment (running on an HPC cluster), what would a reasonable step size and max-iteration limit be to avoid over-fitting of the model?

one more thing: in the case of using WGS Data (no microarray genotyping or imputation), is it fine to include the variants used in step 1 in step 2 since they form part of the greater dataset?

**Comment by Ojami** [comment]
It's difficult to optimize the step size for convergence, you can start with lower values for iteration (e.g. 25) or step size (e.g. 5), but the relevance to over-fitting is another matter. REGENIE step 1 uses CV to avoid that, so I guess you shouldn't be worried about that. 
Yes it's perfectly fine, because REGENIE automatically applies the LOCO approach (reed more in the REGENIE paper) avoiding proximal contamination.

**Comment by Osmluke** [comment]
Ok, perfect, thank you very much!
