### ISSUE TITLE
Questions about the REGENIE v1.0.5.3 

### ISSUE THREAD

**Issue by Jia21** [rgcgithub/regenie#571]
Hi,

I have a question about REGENIE v1.0.5.3. Can Step 1 run by splitting chromosomes such as inputting each chr bed file and output the .loco file for each chromosome? 

Thanks a lot!

**Comment by nikotzoumas** [comment]
Hi, not sure if this works in older versions, but you could run Step 1 with each chromosome file separately, and get separate files eg. step1_chr1.loco, step1_chr2.loco (or .logo.gz if using the --gz option), and then use the filenames to manually create a pred.list file, e.g. containing:
```
Phenotype1 step1_chr1_1.loco
Phenotype2 step1_chr2_1.loco
```
And then use this as the input for the flag --pred in your Step 2 (with all or some chromosomes).

From documentation on the pred.list file: "It has one line per phenotype (in any order) that specifies the name of the phenotype and its corresponding prediction file name. Each phenotype must have exactly one prediction file and phenotype names must match with those in the phenotype file. Phenotypes in this file not included in the analysis are ignored." 

BTW any reason why you're using such an old version? There have been several bug fixes and improvements since.

**Comment by joellembatchou** [comment]
Hi

We recommend running step 1 using all chromosomes to capture genome-wide polygenic effects. If computational burden is a concern, you can try applying more stringent QC to the set of input variants to reduce their number (e.g. LD pruning).

Cheers,
Joelle
